### ISSUE TITLE
How to load e01.py

### ISSUE THREAD

**Issue by papajohn** [Cal-CS-61A-Staff/61a-editor#15]
I'd like to generate a link in the extra lecture page to https://cs61a.org/assets/slides/e01.py, but I'm not sure what that link should be. I tried the following, but they didn't work. Thanks!

https://code.cs61a.org/lece01
https://code.cs61a.org/e01

**Comment by rahularya50** [comment]
Hi Prof. DeNero,

The links are configurable at code.cs61a.org/api/_registry - I've added a link to the extra lecture.

But as it turns out, it seems that the extra lecture code is exceeding the length limit for cookies, which is how I load files. I'll fix this ASAP (tonight), so the link should be ready for tomorrow.

**Comment by papajohn** [comment]
Thanks!

**Comment by rahularya50** [comment]
Alright, https://code.cs61a.org/e01 should work now (though the link isn't yet on the extra lectures page on cs61a.org).

If you've tried the link before, then it may be cached and so will not work. Please try clearing your cache and accessing the link again, and hopefully it should start working!

**Comment by rahularya50** [comment]
This PR makes the extra lectures link up to code.cs61a.org correctly: https://github.com/Cal-CS-61A-Staff/berkeley-cs61a/pull/2720

**Comment by rahularya50** [comment]
The link format has been changed. It's now just `code.cs61a.org/<filename>` - e.g. `code.cs61a.org/01.py`. All previous links will continue to work.
